/*1505107*/


/*---A---*/
SELECT  STREET_ADDRESS || ',' || CITY || STATE_PROVINCE || ',' || POSTAL_CODE "ADDRESS"
FROM LOCATIONS
ORDER BY POSTAL_CODE;


/*---B---*/
SELECT  FIRST_NAME || '.' || ' ' || LAST_NAME "NAME", (SALARY+SALARY*NVL(COMMISSION_PCT,0))*12 "SALARY",
((SALARY+SALARY*NVL(COMMISSION_PCT,0))*12+((SALARY+SALARY*NVL(COMMISSION_PCT,0))*12)*0.1) "RISE"
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'M%' OR LAST_NAME LIKE '%M';


/*---C---*/
SELECT  ADD_MONTHS(TRUNC(HIRE_DATE,'MONTH'),1)-HIRE_DATE-1 "DAYS"
FROM EMPLOYEES;


/*---D---*/
SELECT RPAD(FIRST_NAME,20,'*') "NAME" ,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=10 OR DEPARTMENT_ID=30
ORDER BY LENGTH(FIRST_NAME) DESC;


/*---E---*/
SELECT MANAGER_ID,COUNT(EMPLOYEE_ID),AVG(SALARY) 
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING COUNT(EMPLOYEE_ID)>4 AND AVG(SALARY)>2000 AND MANAGER_ID IS NOT NULL
ORDER BY COUNT(EMPLOYEE_ID) DESC, AVG(SALARY) ASC;


