/*---1---*/
SELECT EMPNAME 
FROM EMPLOYEE
WHERE EMPMSAL<1000;

/*---2---*/
SELECT DEPTNO
FROM EMPLOYEE;

/*---3---*/
SELECT EMPNAME 
FROM EMPLOYEE
WHERE DEPTNO=20 AND EMPMSAL<2500 AND EMPJOB='TRAINER';

/*---4---*/
SELECT EMPNAME "Name",EMPJOB "Job",EMPMSAL "Salary",EMPCOMM "Commission" 
FROM EMPLOYEE
WHERE EMPMSAL>EMPCOMM;

/*---5---*/
SELECT EMPNAME 
FROM EMPLOYEE
WHERE EMPJOB LIKE '%R';

/*---6---*/
SELECT EMPNAME
FROM EMPLOYEE
WHERE EMPNAME LIKE 'J%' OR EMPNAME LIKE 'K%' OR EMPNAME LIKE 'M%';

/*---7---*/
SELECT  EMPNAME
FROM EMPLOYEE
WHERE EMPBDATE<'01-JAN-1960' AND EMPMSAL>1500;

/*---8---*/
SELECT EMPNAME
FROM EMPLOYEE
WHERE EMPCOMM IS NULL;

/*---9---*/
SELECT E1.EMPNAME "NAME",E1.EMPJOB "JOB",(SELECT DEPTNAME FROM DEPARTMENT D2
WHERE D2.DEPTNO=E1.DEPTNO) "DEPARTMENT"

FROM EMPLOYEE E1
WHERE E1.EMPNO= ANY
(
	SELECT D.EMPNO
	FROM DEPARTMENT D
	WHERE D.DEPTLOCATION='NEW YORK'
);

/*---10---*/
SELECT E1.EMPNAME "NAME",E1.EMPJOB 
FROM EMPLOYEE E1
WHERE EMPNO<>ANY
(
	SELECT D1.EMPNO
	FROM DEPARTMENT D1
	WHERE D1.DEPTLOCATION='NEW YORK' OR D1.DEPTLOCATION='CHICAGO'
)

/*---12---*/
SELECT EMPNAME "NAME" 
FROM EMPLOYEE
WHERE EMPMSAL<1500 OR EMPMSAL>3000;

/*---13---*/
SELECT E1.EMPNAME "NAME" 
FROM EMPLOYEE E1
WHERE E1.EMPNO=ANY
(
	SELECT E2.MGRNO 
	FROM EMPLOYEE E2
);

/*---14---*/
SELECT E1.EMPNAME "NAME" 
FROM EMPLOYEE E1
WHERE E1.EMPMSAL>2500 OR
E1.EMPNO=ANY(SELECT  D1.EMPNO FROM DEPARTMENT D1 WHERE D1.DEPTLOCATION='DALLAS')
OR E1.EMPNO=ANY(SELECT E2.MGRNO FROM EMPLOYEE E2);

/*---15---*/
SELECT EMPNAME "NAME",EMPJOB "JOB", EMPMSAL "SALARY" 
FROM EMPLOYEE 
ORDER BY SALARY;




