/*11.1*/

/*A*/
DECLARE
	ENAME VARCHAR2(100);
BEGIN
	SELECT FIRST_NAME INTO ENAME
	FROM EMPLOYEES;
EXCEPTION
	WHEN TOO_MANY_ROWS THEN
		DBMS_OUTPUT.PUT_LINE('MORE THAN ONE ROWS RETURNED');
END;


/*B*/
BEGIN
	INSERT INTO COUNTRIES VALUES('BD','BANGLADESH',7);
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('DUPLICATE VALUE!!!');

	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('UNKNOWN!!!');
END;

