/*11.2*/

/*A*/
DECLARE
	SDATE NUMBER;
	HRDATE DATE;
	FDATE NUMBER;
BEGIN
	FOR HDATE IN (SELECT * FROM EMPLOYEES) 
	LOOP
		SELECT EXTRACT(day FROM SYSDATE) INTO SDATE FROM DUAL;
		HRDATE:=HDATE.HIRE_DATE;
		FDATE:=EXTRACT(day FROM HRDATE);
		
		IF FDATE=SDATE THEN
			DBMS_OUTPUT.PUT_LINE('HAPPY ANNIVERSERY ' || HDATE.FIRST_NAME);
		END IF;
	END LOOP;
END;


