/*Practice 2.2*/


/*---A---*/
SELECT (FIRST_NAME||' '||LAST_NAME) "NAME", HIRE_DATE
FROM EMPLOYEES
WHERE  HIRE_DATE<'01-JAN-1998';


/*---B---*/
SELECT CITY 
FROM LOCATIONS
WHERE COUNTRY_ID=ANY
(
	SELECT COUNTRY_ID
	FROM COUNTRIES
	WHERE COUNTRY_NAME='Canada' OR COUNTRY_NAME='Germany' OR COUNTRY_NAME='United Kingdom'
);


/*---C---*/
SELECT EMPLOYEE_ID, (FIRST_NAME||' '||LAST_NAME) "NAME" 
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;


/*---D---*/
SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'a%';


/*---E---*/
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'S%N';


/*---F---*/
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE MANAGER_ID=100;


/*---G---*/
SELECT (FIRST_NAME||' '||LAST_NAME) "NAME" 
FROM EMPLOYEES
WHERE JOB_ID='AD_PRES' AND SALARY>=23000;


/*---H---*/
SELECT (FIRST_NAME||' '||LAST_NAME) "NAME" 
FROM EMPLOYEES
WHERE LAST_NAME  NOT LIKE '%S%';

/*---I---*/
SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL AND COMMISSION_PCT<=0.3;


/*---J---*/
SELECT  (FIRST_NAME||' '||LAST_NAME) "NAME" 
FROM EMPLOYEES
WHERE HIRE_DATE>='01-JAN-1998';


/*---K---*/
SELECT (FIRST_NAME||' '||LAST_NAME) "NAME"  
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-1998' AND '31-DEC-1998';