/*Practice 2.3*/


/*---A---*/
SELECT (FIRST_NAME||' '||LAST_NAME) "NAME",SALARY,COMMISSION_PCT 
FROM EMPLOYEES
WHERE JOB_ID='AD_PRES'
ORDER BY COMMISSION_PCT ASC,SALARY DESC;


/*---B---*/
SELECT  COUNTRY_NAME
FROM COUNTRIES
ORDER BY COUNTRY_NAME ASC;