/*Practice 4.1*/

/*---A---*/
SELECT MANAGER_ID,COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY MANAGER_ID;


/*---B---*/
SELECT DEPARTMENT_ID,COUNT(SALARY) 
FROM EMPLOYEES
WHERE SALARY>10000
GROUP BY DEPARTMENT_ID;


/*---C----*/
SELECT DEPARTMENT_ID,MIN(SALARY) "MIN",MAX(SALARY) "MAX",ROUND(AVG(SALARY),2) "AVG" 
FROM EMPLOYEES
WHERE DEPARTMENT_ID<>80
GROUP BY DEPARTMENT_ID
ORDER BY AVG DESC,MAX DESC,MIN DESC;